# <u>Kickstarter Campaign</u>

Kickstarter is a company that provides the space for independent artists, creative, innovators, and entrepreneurs to bring their unique projects to life. Kickstarter allows anyone to financially support the project through an online pledging system - this means; anyone can pledge a specific amount of money towards the funding goal of the project. Kickstarter projects (also called campaigns) are all-or-nothing -- meaning, if the funding goal isn't met 100% (or exceeded), the project campaign fails and no funding is provided. The stakes are high - but what is it about certain campaigns that make them succeed while others fail? 

You have joined the marketing team for Kickstarter and you are tasked with exploring the features of several campaigns over the past few years. You are responsible for looking at this dataset and pulling out key insights about the characteristics of Kickstarter campaigns that make them more likely to succeed or fail. The marketing team at Kickstarter has a limited amount of funds to devote to highlighting specific projects, and they want to highlight projects that have the best chance of succeeding (i.e. meeting the funding goal). Can you help them determine who that might be?

Complete the steps below to take a dataset from inception to insights, for the purpose of answering the following two questions:

    1. What kinds of projects should the Kickstarter Marking Team focus their attention on?
    2. Why should the Marketing Team focus their attention in that direction?

After you have combed through the data, your group will put together a report (without visualizations), that clearly answers the two questions above. The Kickstarter dataset is posted to Canvas. Complete the code in the notebook below to complete the project. <b> You are NOT restricted to the steps laid out in this notebook to complete your project, You can conduct additional analyses. This notebook is everything you need to cover, but feel free to expand on these steps!</b>

## <font color=blue>Part 1: Domain Knowledge</font>

Before you begin looking at the data, you need to expand your knowledge of the subject matter. Start by visiting www.kickstarter.com and read all you can about the company. What is the objective of the company? How does it work? What does the project timeline look like? You should research the company until you feel comfortable speaking about the basics of Kickstarter projects. Use the space below (double-click the cell to activate) to write a brief paragraph about what you learned about Kickstarter. 

### <font color=#6AA121>Questions to Answer</font>
1. What is Kickstarter?
2. What is the purpose of Kickstarter?
3. Who are the "backers" of a Kickstarter campaign?
4. How is success determined for a project campaign?

****

### <font color=6AA121>KICKSTARTER INFORMATION</font>

#### Start your paragraph here . . . Be sure to answer all questions in this space!

In [ ]:
# 1)Kickstarter is a company that provides the space for independent artists, creative, innovators, and entrepreneurs 
#to bring their unique projects to life.

# 2)Kickstarter allows anyone to financially support the project through an online pledging system.

# 3)Anyone can pledge a specific amount of money towards the funding goal of the project.

# 4)Kickstarter projects (also called campaigns) are all-or-nothing -- meaning, if the funding goal isn't met 100% 
#(or exceeded), the project campaign fails and no funding is provided.

## <font color=blue>Part 2: Data Import and Cleaning</font>

Now that you are familiar with where the data is coming from, you are ready to start examining the data. The Kickstarter Dataset is a collection of project campaign information from 2016. Data includes information about the project name, length, country of origin, goal, and the amount of money raised, etc. If you open the Kickstarter Dataset in excel, the second tab provides descriptions of each of the columns/variables. Import the dataset into this notebook and follow the steps below to gather information about the data and to clean up the dataset. Use the space below (double-click the cell to activate) to write a brief paragraph describing the dataset and the steps you took while cleaning the data. 

### <font color=#6AA121>Questions to Answer</font>
1. How many columns are in the dataset? How many rows?
2. What type of variables (continuous, categorical) make up this dataset?
3. Which variables have missing values? Are there any duplicate rows?
4. How did you handle the missing data in the dataset?
5. How many rows are in your dataset after handling missing data?
6. Are there any odd or inappropriate values within a column that don't make sense? If so, what are they?
7. What percentage of the each project was funded? In other words, how close were they to reaching the goal? You will need to create a new variable to answer this question.

***

### <font color=blue>DATASET INFORMATION AND CLEANING</font>

#### Start your paragraph here . . . Be sure to answer all questions in this space!

In [2]:
# import "pandas" & "numpy" Python libraries and import Kickstarter dataset


import pandas as pd
import numpy as np

## this is a large dataset, we want to see all rows 
pd.set_option('display.max_rows', None)


df = pd.read_excel("datasets/Kickstarter_Dataset.xlsx")

df.head()

,ID,name,main_category,category,country,currency,launched,deadline,length_days,goal,pledged,usd pledged,backers,state
0,1009317190,French Cuisine,Food,Cookbooks,US,USD,2014-08-09 03:16:02,2014-09-08 00:46:23,29,13730.0,3984.0,3984.000000,46,failed
1,1618024139,HotRod Henry SUPERCHARGED - the ultimate 3D pr...,Technology,3D Printing,AT,EUR,2016-06-16 16:30:33,2016-07-21 23:59:00,35,75000.0,7386.0,1561.784015,31,failed
2,2004838949,PHAbulous Philaments - 3D printing: natural an...,Technology,3D Printing,AT,EUR,2015-07-22 12:08:26,2015-08-21 12:08:26,30,15000.0,3834.0,4152.402045,46,failed
3,258770123,Schokostruder - Chocolate & Liquid Extruder f...,Technology,3D Printing,AT,EUR,2016-01-25 18:48:09,2016-02-24 18:48:09,30,20000.0,18.0,19.435528,6,failed
4,690137136,StarterMate - the 3D printing starter kit for ...,Technology,3D Printing,AT,EUR,2015-09-30 00:26:43,2015-11-09 00:26:43,40,20000.0,2598.0,2908.076574,29,failed

In [3]:
# use the "shape" function to determine the dataset shape (number of rows and columns)


df.shape

(281856, 14)

In [ ]:
# the "df" dataframe has 281,856 rows and 14 columns...

In [4]:
# use the "info" function to determine the dataset features (info) and data types in the "df" dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281856 entries, 0 to 281855
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ID             281856 non-null  int64
 1   name           281821 non-null  object
 2   main_category  281856 non-null  object
 3   category       281856 non-null  object
 4   country        281856 non-null  object
 5   currency       281856 non-null  object
 6   launched       281856 non-null  datetime64[ns]
 7   deadline       281856 non-null  datetime64[ns]
 8   length_days    281856 non-null  int64
 9   goal           281856 non-null  float64
 10  pledged        281856 non-null  float64
 11  usd pledged    281646 non-null  float64
 12  backers        281856 non-null  int64
 13  state          281856 non-null  object
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 30.1+ MB

In [5]:
# use the "isnull" & "sum" functions to determine which variables have missing data 

df.isnull().sum()

ID                 0
name              35
main_category      0
category           0
country            0
currency           0
launched           0
deadline           0
length_days        0
goal               0
pledged            0
usd pledged      210
backers            0
state              0
dtype: int64

In [ ]:
# the "name" & "usd pledged" columns have missing data...

In [6]:
## handling missing data

# create a copy of the original dataset
df1 = df.copy()

## fill all the missing values in "name" with "Unknown Project Name"
df1["name"] = df1["name"].fillna("Unknown Project Name")

# verify these changes
df1.head()

,ID,name,main_category,category,country,currency,launched,deadline,length_days,goal,pledged,usd pledged,backers,state
0,1009317190,French Cuisine,Food,Cookbooks,US,USD,2014-08-09 03:16:02,2014-09-08 00:46:23,29,13730.0,3984.0,3984.000000,46,failed
1,1618024139,HotRod Henry SUPERCHARGED - the ultimate 3D pr...,Technology,3D Printing,AT,EUR,2016-06-16 16:30:33,2016-07-21 23:59:00,35,75000.0,7386.0,1561.784015,31,failed
2,2004838949,PHAbulous Philaments - 3D printing: natural an...,Technology,3D Printing,AT,EUR,2015-07-22 12:08:26,2015-08-21 12:08:26,30,15000.0,3834.0,4152.402045,46,failed
3,258770123,Schokostruder - Chocolate & Liquid Extruder f...,Technology,3D Printing,AT,EUR,2016-01-25 18:48:09,2016-02-24 18:48:09,30,20000.0,18.0,19.435528,6,failed
4,690137136,StarterMate - the 3D printing starter kit for ...,Technology,3D Printing,AT,EUR,2015-09-30 00:26:43,2015-11-09 00:26:43,40,20000.0,2598.0,2908.076574,29,failed

In [7]:
# use the "isnull" & "sum" functions to determine which variables have missing data 

df1.isnull().sum()

ID                 0
name               0
main_category      0
category           0
country            0
currency           0
launched           0
deadline           0
length_days        0
goal               0
pledged            0
usd pledged      210
backers            0
state              0
dtype: int64

In [8]:
# use the "dropna" function to drop all the rows where "usd pledged" data is missing
# and move the results into a variable named "df2"

df2 = df1.dropna(subset=["usd pledged"])

# use the "isnull" & "sum" functions to determine which variables have missing data 
df2.isnull().sum()

ID               0
name             0
main_category    0
category         0
country          0
currency         0
launched         0
deadline         0
length_days      0
goal             0
pledged          0
usd pledged      0
backers          0
state            0
dtype: int64

In [9]:
# use the "info" function to determine the dataset features (info) and data types in the "df2" dataset

df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 281646 entries, 0 to 281855
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ID             281646 non-null  int64
 1   name           281646 non-null  object
 2   main_category  281646 non-null  object
 3   category       281646 non-null  object
 4   country        281646 non-null  object
 5   currency       281646 non-null  object
 6   launched       281646 non-null  datetime64[ns]
 7   deadline       281646 non-null  datetime64[ns]
 8   length_days    281646 non-null  int64
 9   goal           281646 non-null  float64
 10  pledged        281646 non-null  float64
 11  usd pledged    281646 non-null  float64
 12  backers        281646 non-null  int64
 13  state          281646 non-null  object
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 32.2+ MB

In [10]:
# use the "duplicated" & "loc" functions to check for duplicate rows in the "df2" dataset

dupes = df2.duplicated()
df2.loc[dupes]

Empty DataFrame
Columns: [ID, name, main_category, category, country, currency, launched, deadline, length_days, goal, pledged, usd pledged, backers, state]
Index: []

In [ ]:
# there are no duplicate rows...

In [ ]:
# use the "value_counts" function to check for potential inappropriate values in categorical variables
# in the "df2" dataset

In [11]:
df2["state"].value_counts()

failed        168503
successful    113143
Name: state, dtype: int64

In [12]:
df2["main_category"].value_counts()

Film & Video    51108
Music           40868
Publishing      30254
Games           22429
Art             21805
Technology      21444
Design          20032
Food            18899
Fashion         15839
Theater          9340
Photography      8668
Comics           7918
Crafts           6310
Journalism       3537
Dance            3195
Name: main_category, dtype: int64

In [13]:
df2["category"].value_counts()

Product Design        14539
Documentary           13371
Shorts                10786
Music                 10744
Food                   9545
Tabletop Games         8830
Video Games            7871
Film & Video           7813
Fiction                7277
Fashion                6997
Nonfiction             6581
Theater                6476
Art                    6243
Rock                   5852
Children's Books       5148
Indie Rock             5048
Photography            5041
Webseries              4772
Technology             4722
Apparel                4657
Narrative Film         4410
Comics                 4245
Publishing             4128
Apps                   3984
Country & Folk         3821
Web                    3480
Crafts                 3410
Hip-Hop                3062
Design                 2908
Pop                    2763
Hardware               2670
Painting               2641
Public Art             2624
Classical Music        2216
Mixed Media            2187
Games                  2159
Software               2152
Dance                  2127
Illustration           2104
Art Books              2048
Restaurants            2027
Animation              1962
Performance Art        1845
Accessories            1738
World Music            1712
Gadgets                1687
Comic Books            1670
Electronic Music       1659
Drinks                 1615
Jazz                   1579
Comedy                 1537
Sculpture              1491
Drama                  1491
Graphic Design         1474
Journalism             1428
Playing Cards          1376
Food Trucks            1316
Small Batch            1297
Graphic Novels         1197
Mobile Games           1116
Poetry                 1110
Photobooks             1078
Plays                  1066
Periodicals            1041
Digital Art             977
Horror                  870
Farms                   870
Woodworking             842
Conceptual Art          827
People                  812
Faith                   808
DIY                     791
Performances            764
Radio & Podcasts        739
Jewelry                 732
Television              709
Live Games              700
Wearables               688
Musical                 688
Experimental            673
Festivals               642
DIY Electronics         602
Events                  594
Academic                590
Ready-to-wear           581
Spaces                  574
Young Adult             568
Fine Art                562
Metal                   553
Places                  551
Footwear                537
Architecture            531
Science Fiction         517
Print                   516
Music Videos            516
Anthologies             512
Thrillers               495
Action                  495
3D Printing             455
Webcomics               429
Nature                  425
Sound                   389
Robots                  380
Cookbooks               372
Vegan                   370
Installations           350
Farmer's Markets        319
Childrenswear           315
R&B                     312
Candles                 307
Video                   302
Flight                  299
Interactive Design      283
Audio                   277
Zines                   258
Camera Equipment        251
Family                  242
Immersive               239
Community Gardens       235
Fantasy                 227
Civic Design            226
Space Exploration       225
Gaming Hardware         218
Punk                    216
Kids                    214
Calendars               209
Ceramics                201
Animals                 199
Literary Journals       196
Couture                 191
Blues                   189
Textiles                175
Fabrication Tools       168
Movie Theaters          166
Makerspaces             164
Bacon                   163
Puzzles                 159
Printing                148
Stationery              144
Photo                   142
Video Art               140
Knitting                135
Romance                 131
Crochet                 123
Workshops               119
Translations            115
Glass                   109
Pet Fashion              91
Latin                    89
Typography               71
Embroidery               70
Pottery                  65
Quilts                   64
Weaving                  59
Residencies              52
Letterpress              34
Chiptune                 31
Taxidermy                 9
Name: category, dtype: int64

In [14]:
df2["country"].value_counts()

US    229826
GB     23877
CA      9912
AU      5195
DE      2131
NL      1873
FR      1559
IT      1394
ES      1090
SE      1066
NZ       993
DK       672
IE       473
NO       430
CH       389
BE       329
AT       283
SG        70
HK        47
LU        33
MX         4
Name: country, dtype: int64

In [15]:
df2["currency"].value_counts()

USD    229826
GBP     23877
CAD      9912
EUR      9165
AUD      5195
SEK      1066
NZD       993
DKK       672
NOK       430
CHF       389
SGD        70
HKD        47
MXN         4
Name: currency, dtype: int64

In [16]:
df2.head(2)

,ID,name,main_category,category,country,currency,launched,deadline,length_days,goal,pledged,usd pledged,backers,state
0,1009317190,French Cuisine,Food,Cookbooks,US,USD,2014-08-09 03:16:02,2014-09-08 00:46:23,29,13730.0,3984.0,3984.000000,46,failed
1,1618024139,HotRod Henry SUPERCHARGED - the ultimate 3D pr...,Technology,3D Printing,AT,EUR,2016-06-16 16:30:33,2016-07-21 23:59:00,35,75000.0,7386.0,1561.784015,31,failed

In [17]:
# use the "drop" function to drop/delete unneeded columns (project ID, name, pledged, launched, deadline)
# and copy the results into a variable named "df3"
# you will use usd pledged from now on

df3 = df2.drop(columns = ["ID", "name", "pledged", "launched", "deadline"])

#use the "head" function to view the changes to the "df3" dataset
df3.head(2)

,main_category,category,country,currency,length_days,goal,usd pledged,backers,state
0,Food,Cookbooks,US,USD,29,13730.0,3984.000000,46,failed
1,Technology,3D Printing,AT,EUR,35,75000.0,1561.784015,31,failed

In [18]:
# create a new column named "pct_funded" (percentage of project that was funded) to the "df3" dataset
# how close were they to reaching the goal?

df3["pct_funded"] = (df3["usd pledged"]/df3["goal"])*100

df3.head()

,main_category,category,country,currency,length_days,goal,usd pledged,backers,state,pct_funded
0,Food,Cookbooks,US,USD,29,13730.0,3984.000000,46,failed,29.016752
1,Technology,3D Printing,AT,EUR,35,75000.0,1561.784015,31,failed,2.082379
2,Technology,3D Printing,AT,EUR,30,15000.0,4152.402045,46,failed,27.682680
3,Technology,3D Printing,AT,EUR,30,20000.0,19.435528,6,failed,0.097178
4,Technology,3D Printing,AT,EUR,40,20000.0,2908.076574,29,failed,14.540383

In [19]:
# save your clean dataset to your "datasets" folder as an Excel file (xlsx)
# re-name the dataset as "Kickstarter_Clean"
# this cleaned version to work in visualization (later)

#df3.to_excel("datasets/Kickstarter_Clean.xlsx", index = False)

df3.to_excel("datasets/Kickstarter_Clean.xlsx")

## <font color=blue>Part 3: Exploratory Analysis</font>

With a clean dataset, you are now ready to start exploring the variables in your dataset. Don't worry about how your variables relate to each other - we will cover that in the next section. For now, it's more important that you get a clear sense of the variable characteristics on their own. Follow the steps below to explore all of the variables within your dataset and preform descriptive statistics. In addition to the descriptive statistics, you are tasked with creating a summary report related to your results (later in PowerBI). Stylistic choices related to the visualizations is up to your group. Use the space below (double-click the cell to activate) to write a brief paragraph describing the steps you took to explore the data. 

### <font color=#6AA121>Questions to Answer</font>
1.	What is the average (mean) for the following variables: goal, usd pledged, backers, and length? 
2.	What is the maximum value, minimum value, and range for the following variables: goal, usd pledged, backers, and length?
3.	What is the most common (mode) length for campaign projects?
4.	Considering the categorical variables, what is the most frequent main category group? How many projects are classified under this category? What is the most frequent sub-category? How many projects are classified under this category? 
5.	Considering the categorical variables, what is the least frequent main category group? How many projects are classified under this category? What is the least frequent sub-category? How many projects are classified under this category? 
6.	Which country has started the most Kickstarter campaigns?
7.	How many projects have failed? How many projects have succeeded?

### <font color=blue>Items to include in your report</font> 
* Number of Projects by Main Category
* Number of projects by State (outcome)
* Number of projects from each country
* Number of successful projects and failed projects by Main Category

***

### <font color=#blue>EXPLORATORY DATA ANALYSIS</font>

#### Start your paragraph here . . . Be sure to answer all questions in this space!

In [20]:
# use the "describe" function to view the descriptive statistics for numeric variables in the "df3" dataset

df3.describe()

         length_days          goal   usd pledged        backers    pct_funded
count  281646.000000  2.816460e+05  2.816460e+05  281646.000000  2.816460e+05
mean       33.976520  4.181597e+04  8.575848e+03     111.934801  2.762000e+02
std        12.894187  1.043830e+06  8.916948e+04     996.631624  1.826263e+04
min         1.000000  1.000000e-02  0.000000e+00       0.000000  0.000000e+00
25%        30.000000  2.000000e+03  4.000000e+01       2.000000  6.000000e-01
50%        30.000000  5.000000e+03  6.910000e+02      15.000000  1.661484e+01
75%        36.000000  1.500000e+04  4.109040e+03      62.000000  1.080828e+02
max        92.000000  1.000000e+08  2.033899e+07  219382.000000  5.526657e+06

In [ ]:
# What is the average (mean) for the following variables: goal, usd pledged, backers, and length? 

# the average (mean) for "goal" is 41,815.97

# the average (mean) for "usd pledged" is 8,575.848

# the average (mean) for "length_days" is 33.976520

In [ ]:
# What is the maximum value, minimum value, and range for the following variables: goal, usd pledged, 
# backers, and length?

# for "goal":
# maximum value: 100,000,000.0
# minimum value: 0.01
# range: 99,999,999.99

# for "usd pledged"
# maximum value: 20,338,986.27
# minimum value: 0.0
# range: 20,338,986.27

# for "backers"
# maximum value: 219,382
# minimum value: 0.0
# range: 219,382

# for "length_days"
# maximum value: 92
# minimum value: 0
# range: 92

In [21]:
# What is the most common (mode) length for campaign projects?

# use the "mode" functino to discover the most common occurrence in the "length_days" column

df3["length_days"].mode()

0    30
dtype: int64

In [ ]:
# the most common (mode) length for campaign projects is 30 days...

In [ ]:
# Considering the categorical variables, what is the most frequent main category group? How many projects are 
# classified under this category? What is the most frequent sub-category? How many projects are classified under 
# this category? 

# Considering the categorical variables, what is the least frequent main category group? How many projects are 
# classified under this category? What is the least frequent sub-category? How many projects are classified under 
# this category? 

# use the "value_counts" function to discover answers to the questions in this cell

In [22]:
df3["main_category"].value_counts()

Film & Video    51108
Music           40868
Publishing      30254
Games           22429
Art             21805
Technology      21444
Design          20032
Food            18899
Fashion         15839
Theater          9340
Photography      8668
Comics           7918
Crafts           6310
Journalism       3537
Dance            3195
Name: main_category, dtype: int64

In [23]:
df3["category"].value_counts()

Product Design        14539
Documentary           13371
Shorts                10786
Music                 10744
Food                   9545
Tabletop Games         8830
Video Games            7871
Film & Video           7813
Fiction                7277
Fashion                6997
Nonfiction             6581
Theater                6476
Art                    6243
Rock                   5852
Children's Books       5148
Indie Rock             5048
Photography            5041
Webseries              4772
Technology             4722
Apparel                4657
Narrative Film         4410
Comics                 4245
Publishing             4128
Apps                   3984
Country & Folk         3821
Web                    3480
Crafts                 3410
Hip-Hop                3062
Design                 2908
Pop                    2763
Hardware               2670
Painting               2641
Public Art             2624
Classical Music        2216
Mixed Media            2187
Games                  2159
Software               2152
Dance                  2127
Illustration           2104
Art Books              2048
Restaurants            2027
Animation              1962
Performance Art        1845
Accessories            1738
World Music            1712
Gadgets                1687
Comic Books            1670
Electronic Music       1659
Drinks                 1615
Jazz                   1579
Comedy                 1537
Sculpture              1491
Drama                  1491
Graphic Design         1474
Journalism             1428
Playing Cards          1376
Food Trucks            1316
Small Batch            1297
Graphic Novels         1197
Mobile Games           1116
Poetry                 1110
Photobooks             1078
Plays                  1066
Periodicals            1041
Digital Art             977
Horror                  870
Farms                   870
Woodworking             842
Conceptual Art          827
People                  812
Faith                   808
DIY                     791
Performances            764
Radio & Podcasts        739
Jewelry                 732
Television              709
Live Games              700
Wearables               688
Musical                 688
Experimental            673
Festivals               642
DIY Electronics         602
Events                  594
Academic                590
Ready-to-wear           581
Spaces                  574
Young Adult             568
Fine Art                562
Metal                   553
Places                  551
Footwear                537
Architecture            531
Science Fiction         517
Print                   516
Music Videos            516
Anthologies             512
Thrillers               495
Action                  495
3D Printing             455
Webcomics               429
Nature                  425
Sound                   389
Robots                  380
Cookbooks               372
Vegan                   370
Installations           350
Farmer's Markets        319
Childrenswear           315
R&B                     312
Candles                 307
Video                   302
Flight                  299
Interactive Design      283
Audio                   277
Zines                   258
Camera Equipment        251
Family                  242
Immersive               239
Community Gardens       235
Fantasy                 227
Civic Design            226
Space Exploration       225
Gaming Hardware         218
Punk                    216
Kids                    214
Calendars               209
Ceramics                201
Animals                 199
Literary Journals       196
Couture                 191
Blues                   189
Textiles                175
Fabrication Tools       168
Movie Theaters          166
Makerspaces             164
Bacon                   163
Puzzles                 159
Printing                148
Stationery              144
Photo                   142
Video Art               140
Knitting                135
Romance                 131
Crochet                 123
Workshops               119
Translations            115
Glass                   109
Pet Fashion              91
Latin                    89
Typography               71
Embroidery               70
Pottery                  65
Quilts                   64
Weaving                  59
Residencies              52
Letterpress              34
Chiptune                 31
Taxidermy                 9
Name: category, dtype: int64

In [ ]:
# the most frequent main category group is "Film & Video"...
# 51,108 projects are classified under this category...

# the most frequent sub-category group is "Product Design"...
# 14,539 projects are classified under this sub-category...

# the least frequent main category group is "Dance"...
# 3,195 projects are classified under this category...

# the least frequent sub-category group is "Taxidermy"...
# 9 projects are classified under this sub-category...

In [24]:
# Which country has started the most Kickstarter campaigns?

# use the "value_counts" function to discover the answer to the question in this cell
df3["country"].value_counts()

US    229826
GB     23877
CA      9912
AU      5195
DE      2131
NL      1873
FR      1559
IT      1394
ES      1090
SE      1066
NZ       993
DK       672
IE       473
NO       430
CH       389
BE       329
AT       283
SG        70
HK        47
LU        33
MX         4
Name: country, dtype: int64

In [ ]:
# the US (USA) has started the most Kickstarter projects (229,826)...

In [25]:
# How many projects have failed? How many projects have succeeded?

#use the "value_counts" function to discover the answer to the question in this cell
df3["state"].value_counts()

failed        168503
successful    113143
Name: state, dtype: int64

In [ ]:
# 168,503 projects have failed...
# 113,143 projects have been successful...

In [26]:
# Number of successful projects and failed projects by Main Category

# use the "crosstab" function to see the number of failed and successful fundraisings for each main category

pd.crosstab(df3["state"], df3["main_category"])

main_category,Art,Comics,Crafts,Dance,Design,Fashion,Film & Video,Food,Games,Journalism,Music,Photography,Publishing,Technology,Theater
state,,,,,,,,,,,,,,,
failed,12128,3411,4637,1091,12063,11520,29696,13632,13033,2667,19172,5760,19973,16377,3343
successful,9677,4507,1673,2104,7969,4319,21412,5267,9396,870,21696,2908,10281,5067,5997

In [27]:
#use the "head" function to view the column names

df3.head(2)

,main_category,category,country,currency,length_days,goal,usd pledged,backers,state,pct_funded
0,Food,Cookbooks,US,USD,29,13730.0,3984.000000,46,failed,29.016752
1,Technology,3D Printing,AT,EUR,35,75000.0,1561.784015,31,failed,2.082379

In [28]:
# use the "describe" function to view the descriptive statistics for numeric variables in the "df3" dataset

df3.describe()

         length_days          goal   usd pledged        backers    pct_funded
count  281646.000000  2.816460e+05  2.816460e+05  281646.000000  2.816460e+05
mean       33.976520  4.181597e+04  8.575848e+03     111.934801  2.762000e+02
std        12.894187  1.043830e+06  8.916948e+04     996.631624  1.826263e+04
min         1.000000  1.000000e-02  0.000000e+00       0.000000  0.000000e+00
25%        30.000000  2.000000e+03  4.000000e+01       2.000000  6.000000e-01
50%        30.000000  5.000000e+03  6.910000e+02      15.000000  1.661484e+01
75%        36.000000  1.500000e+04  4.109040e+03      62.000000  1.080828e+02
max        92.000000  1.000000e+08  2.033899e+07  219382.000000  5.526657e+06

In [31]:
## calculate the inter-quartile range for all numeric variables

# iqr = df[" "].max() - df[" "].min()

In [29]:
# use the "copy" function to place a copy of the "df3" dataset into a variable named "df_length_days"...this dataset 
# will be used to detect and remove outliers using the Interquartile Range (IQR)...

df_length_days = df3.copy()

In [30]:
# Calculate quartiles for the values in the "length_days" column

q1 = df_length_days["length_days"].quantile(.25)
q3 = df_length_days["length_days"].quantile(.75)


# calculate the Interquartile Range (IQR)...
iqr = q3 - q1


# determine/calculate the outlier fences...
top = q3 + (iqr * 1.5)
bottom = q1 - (iqr * 1.5)


# display the Interquartile Range (IQR), the top & bottom outlier fences...

print("q1=", q1, "q3=", q3, "iqr=", iqr, "bottom=", bottom, "top=", top)

q1= 30.0 q3= 36.0 iqr= 6.0 bottom= 21.0 top= 45.0

In [ ]:
## Determine the index locations for rows that fall outside of outlier fences (top & bottom)

#iqr_outliers_length_days = df_length_days[(df_length_days["length_days"] > top) | (df_length_days["length_days"] < bottom)].index

# display the index(s) that contain values in the "ROOMS" column that are outliers...

#print(iqr_outliers_length_days)

In [ ]:
# drop the rows that contain the outliers in the "dfq" dataset with the associated index values...
#df_length_days = df_length_days.drop(iqr_outliers_length_days)


# check the shape of the updated "dfq" dataframe...
#print(df_length_days.shape)

In [ ]:
## Re-check the shape of the dataframe, how many rows were dropped?
#print(df3.shape)

In [31]:
# use the "copy" function to place a copy of the "df3" dataset into a variable named "df_goal"...this dataset 
# will be used to detect and remove outliers using the Interquartile Range (IQR)...

df_goal = df3.copy()

In [32]:
# Calculate quartiles for the values in the "goal" column

q1 = df_goal["goal"].quantile(.25)
q3 = df_goal["goal"].quantile(.75)


# calculate the Interquartile Range (IQR)...
iqr = q3 - q1


# determine/calculate the outlier fences...
top = q3 + (iqr * 1.5)
bottom = q1 - (iqr * 1.5)


# display the Interquartile Range (IQR), the top & bottom outlier fences...

print("q1=", q1, "q3=", q3, "iqr=", iqr, "bottom=", bottom, "top=", top)

q1= 2000.0 q3= 15000.0 iqr= 13000.0 bottom= -17500.0 top= 34500.0

In [33]:
# use the "copy" function to place a copy of the "df3" dataset into a variable named "df_usd_pledged"...this dataset 
# will be used to detect and remove outliers using the Interquartile Range (IQR)...

df_usd_pledged = df3.copy()

In [34]:
# Calculate quartiles for the values in the "usd pledged" column

q1 = df_usd_pledged["usd pledged"].quantile(.25)
q3 = df_usd_pledged["usd pledged"].quantile(.75)


# calculate the Interquartile Range (IQR)...
iqr = q3 - q1


# determine/calculate the outlier fences...
top = q3 + (iqr * 1.5)
bottom = q1 - (iqr * 1.5)


# display the Interquartile Range (IQR), the top & bottom outlier fences...

print("q1=", q1, "q3=", q3, "iqr=", iqr, "bottom=", bottom, "top=", top)

q1= 40.0 q3= 4109.04048425 iqr= 4069.04048425 bottom= -6063.560726375001 top= 10212.601210625002

In [35]:
# use the "copy" function to place a copy of the "df3" dataset into a variable named "df_backers"...this dataset 
# will be used to detect and remove outliers using the Interquartile Range (IQR)...

df_backers = df3.copy()

In [36]:
# Calculate quartiles for the values in the "backers" column

q1 = df_backers["backers"].quantile(.25)
q3 = df_backers["backers"].quantile(.75)


# calculate the Interquartile Range (IQR)...
iqr = q3 - q1


# determine/calculate the outlier fences...
top = q3 + (iqr * 1.5)
bottom = q1 - (iqr * 1.5)


# display the Interquartile Range (IQR), the top & bottom outlier fences...

print("q1=", q1, "q3=", q3, "iqr=", iqr, "bottom=", bottom, "top=", top)

q1= 2.0 q3= 62.0 iqr= 60.0 bottom= -88.0 top= 152.0

In [37]:
# use the "copy" function to place a copy of the "df3" dataset into a variable named "df_pct_funded"...this dataset 
# will be used to detect and remove outliers using the Interquartile Range (IQR)...

df_pct_funded = df3.copy()

In [38]:
# Calculate quartiles for the values in the "pct_funded" column

q1 = df_pct_funded["pct_funded"].quantile(.25)
q3 = df_pct_funded["pct_funded"].quantile(.75)


# calculate the Interquartile Range (IQR)...
iqr = q3 - q1


# determine/calculate the outlier fences...
top = q3 + (iqr * 1.5)
bottom = q1 - (iqr * 1.5)


# display the Interquartile Range (IQR), the top & bottom outlier fences...

print("q1=", q1, "q3=", q3, "iqr=", iqr, "bottom=", bottom, "top=", top)

q1= 0.6 q3= 108.08283823529413 iqr= 107.48283823529414 bottom= -160.6242573529412 top= 269.30709558823537

In [ ]:
## frequency of categorical variable groups

df[" "].val-----------

## <font color=#blue>Part 4: Variable Relationships</font>

It's time to explore the relationships between variables and answer some of the critical questions for the project. Your dependent/outcome variable is <b>STATE</b> - this is the variable that captures if the project was successful or not. In addition to exploring the relationships between your other independent variables, you want to pay close attention to the relationship between your independent variables and state. Follow the steps below to explore the relationships between your variables. In addition, you are tasked with creating a summary report (later, visualizations in PowerBI) related to your results. Stylistic choices related to the visualizations is up to your group. Use the space below (double-click the cell to activate) to write a brief paragraph describing the steps you took to determine variable relationships. 

### <font color=#6AA121>Questions to Answer</font>
1.	How correlated are the numeric variables within this dataset? Create a correlation matrix to find out. Is anything highly correlated?
2.	What is the average amount of money pledged across each of the main categories? What about across the following: sub-category, country, currency, and state? Which main category is the most profitable? 
3.	What is the average number of backers across each of the main categories? What about across the following: sub-category, country, currency, and state? Which main category is the most popular?
4.	What percentage of projects succeed and fail across each of the main categories?
5.	Which of the main categories have the highest success rate (top 3)? Which of the sub-categories have the highest success rate (top 3)?
6.	What is the average duration of a campaign for projects that succeed? What is the average duration for projects that fail?
7.  What is the average funding goal of a campaign for projects that succeed? What is the average funding goal for projects that fail?


### <font color=#blue>Visualizations to Create</font> 
* Average Pledge by Main Category
* Average Num Backers by Main Category
* Average Pledge by State
* Average Num Backers by State
* Average Funding Goal by Main Category
* Average Funding Goal by State
* Average Percentage of Funding Collected by Main Category

***

### <font color=#6AA121>RELATIONSHIPS BETWEEN VARIABLES</font>

#### Start your paragraph here . . . Be sure to answer all questions in this space!

In [39]:
## create a correlation matrix for the continuous variables

# How correlated are the numeric variables within this dataset? Create a correlation 
# matrix to find out. Is anything highly correlated?

# use the "corr" function to view the relationships between/amongst the numeric variables
df3.corr()

             length_days      goal  usd pledged   backers  pct_funded
length_days     1.000000  0.022077     0.006316 -0.001391   -0.002499
goal            0.022077  1.000000     0.007617  0.006090   -0.000561
usd pledged     0.006316  0.007617     1.000000  0.716784    0.010074
backers        -0.001391  0.006090     0.716784  1.000000    0.017322
pct_funded     -0.002499 -0.000561     0.010074  0.017322    1.000000

In [ ]:
# there is a high correlation between "usd pledged" & "backers"...

In [27]:
df3.head(2)

,main_category,category,country,currency,length_days,goal,usd pledged,backers,state,pct_funded
0,Food,Cookbooks,US,USD,29,13730.0,3984.000000,46,failed,29.016752
1,Technology,3D Printing,AT,EUR,35,75000.0,1561.784015,31,failed,2.082379

In [ ]:
## average pledge across categoricial variables (groupby)

#use the "groupby" function view the following results

In [28]:
df3["usd pledged"].groupby(df3["main_category"]).mean()

main_category
Art              3069.410309
Comics           6832.580096
Crafts           1514.296337
Dance            3424.076079
Design          23132.730636
Fashion          5665.158035
Film & Video     6518.644822
Food             5221.043908
Games           22622.060660
Journalism       2793.559315
Music            3930.182092
Photography      3265.703688
Publishing       3206.302548
Technology      20898.350418
Theater          4018.430797
Name: usd pledged, dtype: float64

In [29]:
df3["usd pledged"].groupby(df3["category"]).mean()

category
3D Printing           70321.848632
Academic               2003.564080
Accessories            7047.600829
Action                 4128.312842
Animals                2382.214298
Animation             10161.303969
Anthologies            9707.767801
Apparel                4840.655465
Apps                   1589.148271
Architecture           5110.371215
Art                    3547.346218
Art Books              8497.157849
Audio                  3798.740964
Bacon                  1598.635068
Blues                  3901.857626
Calendars              3274.572065
Camera Equipment      71126.629373
Candles                 605.679972
Ceramics               4889.230446
Children's Books       3204.049558
Childrenswear          3730.010306
Chiptune              19654.133498
Civic Design          10104.483750
Classical Music        4528.904938
Comedy                 6181.137441
Comic Books            3277.407865
Comics                 7009.820014
Community Gardens      1774.361231
Conceptual Art         1682.404396
Cookbooks              5230.822925
Country & Folk         4739.995996
Couture                1534.816551
Crafts                 1635.011491
Crochet                 344.568518
DIY                     933.673297
DIY Electronics       26395.598901
Dance                  3618.409594
Design                13509.361754
Digital Art            2068.192840
Documentary            9012.627707
Drama                  4317.194804
Drinks                 6606.220018
Electronic Music       2671.848762
Embroidery              618.892421
Events                 1709.839167
Experimental           1879.680929
Fabrication Tools     38635.618952
Faith                  4223.476944
Family                 5090.511233
Fantasy               11865.339980
Farmer's Markets       1903.061146
Farms                  3744.831300
Fashion                5852.238444
Festivals              2992.783911
Fiction                1558.491226
Film & Video           4930.303051
Fine Art               2461.953439
Flight                28325.768377
Food                   6240.742036
Food Trucks            2112.549996
Footwear              15131.907236
Gadgets               29106.489521
Games                  7741.528588
Gaming Hardware       69561.516705
Glass                  1513.935062
Graphic Design         5852.275416
Graphic Novels         7963.044127
Hardware              44317.869397
Hip-Hop                1225.317680
Horror                 5671.410567
Illustration           3090.818141
Immersive              4941.707966
Indie Rock             3985.325850
Installations          4423.914391
Interactive Design     5249.699127
Jazz                   4499.483700
Jewelry                2776.702660
Journalism             3076.977927
Kids                   4453.162691
Knitting               3991.926166
Latin                  3797.561608
Letterpress            5834.528939
Literary Journals      3035.786078
Live Games             1667.651710
Makerspaces            7046.755159
Metal                  2322.802257
Mixed Media            2866.891416
Mobile Games           1066.053893
Movie Theaters         8178.006865
Music                  4782.225743
Music Videos           1888.110207
Musical                5213.545079
Narrative Film        11369.790324
Nature                 1441.599734
Nonfiction             2948.978014
Painting               1862.313411
People                 2031.026196
Performance Art        2340.126200
Performances           3067.980283
Periodicals            5660.466840
Pet Fashion            3085.858602
Photo                  1814.252706
Photobooks             7073.492690
Photography            3195.777514
Places                  821.104104
Playing Cards          7206.851421
Plays                  2891.757038
Poetry                 1289.202604
Pop                    4030.155877
Pottery                3583.771604
Print                  2590.594711
Printing                865.445505
Product Design        27991.847656
Public Art             4238.759408
Publishing             3414.288085
Punk                   1836.191462
Puzzles                5855.381654
Quilts                 1647.641411
R&B                    2043.620037
Radio & Podcasts       7464.351176
Ready-to-wear          3585.828072
Residencies            2963.146585
Restaurants            4615.734552
Robots                31186.770102
Rock                   3390.401865
Romance                3861.684408
Science Fiction        8706.260996
Sculpture              3315.002704
Shorts                 3482.595222
Small Batch            3772.465191
Software               4126.172203
Sound                 66289.121490
Space Exploration     28297.454583
Spaces                 7374.277221
Stationery             1379.982363
Tabletop Games        31866.666273
Taxidermy              4071.061114
Technology            20652.934517
Television            11160.145077
Textiles               1709.769996
Theater                4050.061876
Thrillers              4813.604712
Translations           2615.556503
Typography            28549.630735
Vegan                  5787.616581
Video                  1407.668924
Video Art              3329.087411
Video Games           22986.210000
Wearables             47650.043765
Weaving                1029.554598
Web                    3376.823987
Webcomics             12360.386881
Webseries              4355.481034
Woodworking            1549.588085
Workshops              1357.862474
World Music            3702.566343
Young Adult            1383.475593
Zines                  2125.691922
Name: usd pledged, dtype: float64

In [30]:
df3["usd pledged"].groupby(df3["country"]).mean()

country
AT     9323.329982
AU     4870.551735
BE     5558.685332
CA     6276.386389
CH     8129.832529
DE     8366.607351
DK     5776.047339
ES     4123.306576
FR    11239.006871
GB     6910.615376
HK     2916.330505
IE     4781.257653
IT     4492.361917
LU     4329.165422
MX        8.136906
NL     5412.893977
NO     3355.555461
NZ     4143.385873
SE     4611.153023
SG     3139.606720
US     9058.345174
Name: usd pledged, dtype: float64

In [31]:
df3["usd pledged"].groupby(df3["currency"]).mean()

currency
AUD    4870.551735
CAD    6276.386389
CHF    8129.832529
DKK    5776.047339
EUR    6886.815741
GBP    6910.615376
HKD    2916.330505
MXN       8.136906
NOK    3355.555461
NZD    4143.385873
SEK    4611.153023
SGD    3139.606720
USD    9058.345174
Name: usd pledged, dtype: float64

In [32]:
df3["usd pledged"].groupby(df3["state"]).mean()

state
failed         1279.467288
successful    19442.292414
Name: usd pledged, dtype: float64

In [ ]:
## average number of backers across categorical variables (groupby)

In [33]:
df3["backers"].groupby(df3["main_category"]).mean()

main_category
Art              42.541206
Comics          145.676812
Crafts           29.562441
Dance            45.290454
Design          268.927566
Fashion          69.507418
Film & Video     73.161697
Food             59.249431
Games           386.230282
Journalism       43.399774
Music            57.797494
Photography      40.766036
Publishing       57.901567
Technology      187.457750
Theater          49.613383
Name: backers, dtype: float64

In [34]:
df3["backers"].groupby(df3["category"]).mean()

category
3D Printing           273.092308
Academic               30.544068
Accessories            99.114499
Action                 59.240404
Animals                34.532663
Animation             144.169215
Anthologies           244.378906
Apparel                56.851836
Apps                   26.027861
Architecture           54.474576
Art                    46.567355
Art Books             130.134277
Audio                  57.790614
Bacon                  27.803681
Blues                  51.968254
Calendars              97.803828
Camera Equipment      409.892430
Candles                13.941368
Ceramics               52.522388
Children's Books       59.756410
Childrenswear          48.425397
Chiptune              498.387097
Civic Design          112.230088
Classical Music        54.523466
Comedy                 92.905660
Comic Books            89.528144
Comics                140.908834
Community Gardens      21.817021
Conceptual Art         29.964933
Cookbooks             100.599462
Country & Folk         67.380005
Couture                14.141361
Crafts                 33.384751
Crochet                 8.951220
DIY                    19.600506
DIY Electronics       314.456811
Dance                  47.911142
Design                182.312586
Digital Art            36.511771
Documentary            98.047042
Drama                  38.467471
Drinks                 63.926316
Electronic Music       48.400241
Embroidery             13.214286
Events                 21.774411
Experimental           29.133730
Fabrication Tools      86.767857
Faith                  47.378713
Family                 48.727273
Fantasy               143.211454
Farmer's Markets       19.003135
Farms                  34.874713
Fashion                74.479062
Festivals              39.858255
Fiction                30.908754
Film & Video           53.579291
Fine Art               29.224199
Flight                162.337793
Food                   72.000314
Food Trucks            23.356383
Footwear              149.713222
Gadgets               347.641375
Games                 101.226494
Gaming Hardware       467.385321
Glass                  19.844037
Graphic Design        111.395522
Graphic Novels        166.026734
Hardware              369.767790
Hip-Hop                21.943174
Horror                 50.002299
Illustration           64.163498
Immersive              51.665272
Indie Rock             63.709588
Installations          53.734286
Interactive Design     52.261484
Jazz                   59.378721
Jewelry                27.879781
Journalism             48.015406
Kids                   66.504673
Knitting               66.785185
Latin                  38.977528
Letterpress            91.941176
Literary Journals      76.270408
Live Games             23.134286
Makerspaces            72.554878
Metal                  49.936709
Mixed Media            33.124371
Mobile Games           20.528674
Movie Theaters         94.518072
Music                  68.676657
Music Videos           27.253876
Musical                54.311047
Narrative Film        115.330159
Nature                 17.705882
Nonfiction             47.689409
Painting               22.831882
People                 30.724138
Performance Art        32.130623
Performances           41.119110
Periodicals            99.889529
Pet Fashion            33.879121
Photo                  26.788732
Photobooks             79.608534
Photography            40.532037
Places                 13.522686
Playing Cards         182.490552
Plays                  37.335835
Poetry                 26.572072
Pop                    57.358306
Pottery                58.215385
Print                  45.936047
Printing               22.277027
Product Design        316.092372
Public Art             57.112424
Publishing             61.768411
Punk                   37.449074
Puzzles               142.264151
Quilts                 23.390625
R&B                    27.605769
Radio & Podcasts      166.995940
Ready-to-wear          36.034423
Residencies            40.288462
Restaurants            39.533300
Robots                199.255263
Rock                   51.092960
Romance                44.725191
Science Fiction       100.930368
Sculpture              41.692153
Shorts                 39.051085
Small Batch            54.214341
Software               87.462361
Sound                 399.655527
Space Exploration     387.115556
Spaces                 80.831010
Stationery             54.944444
Tabletop Games        478.161721
Taxidermy              48.555556
Technology            187.672173
Television             93.519041
Textiles               24.451429
Theater                50.660593
Thrillers              43.109091
Translations           40.626087
Typography            395.042254
Vegan                  95.272973
Video                  17.450331
Video Art              26.757143
Video Games           483.715157
Wearables             431.093023
Weaving                17.745763
Web                    56.842241
Webcomics             275.403263
Webseries              60.160939
Woodworking            22.099762
Workshops              21.630252
World Music            58.424650
Young Adult            23.413732
Zines                  53.453488
Name: backers, dtype: float64

In [35]:
df3["backers"].groupby(df3["country"]).mean()

country
AT     69.727915
AU     82.111453
BE     50.629179
CA     97.199758
CH     76.814910
DE    100.707180
DK     70.949405
ES     71.709174
FR    126.205901
GB     88.638481
HK     68.595745
IE     56.473573
IT     48.080344
LU     36.969697
MX      9.250000
NL     61.481580
NO     39.090698
NZ     67.182276
SE     80.296435
SG    180.557143
US    117.571350
Name: backers, dtype: float64

In [36]:
df3["backers"].groupby(df3["currency"]).mean()

currency
AUD     82.111453
CAD     97.199758
CHF     76.814910
DKK     70.949405
EUR     80.308347
GBP     88.638481
HKD     68.595745
MXN      9.250000
NOK     39.090698
NZD     67.182276
SEK     80.296435
SGD    180.557143
USD    117.571350
Name: backers, dtype: float64

In [37]:
df3["backers"].groupby(df3["state"]).mean()

state
failed         16.768301
successful    253.665538
Name: backers, dtype: float64

In [ ]:
## averages of all numeric variables grouped by state (groupby)

# use the "groupby" function to view the following results

In [38]:
df3.head(2)

,main_category,category,country,currency,length_days,goal,usd pledged,backers,state,pct_funded
0,Food,Cookbooks,US,USD,29,13730.0,3984.000000,46,failed,29.016752
1,Technology,3D Printing,AT,EUR,35,75000.0,1561.784015,31,failed,2.082379

In [39]:
df3["length_days"].groupby(df3["state"]).mean()

state
failed        35.181658
successful    32.181717
Name: length_days, dtype: float64

In [40]:
df3["goal"].groupby(df3["state"]).mean()

state
failed        63432.182763
successful     9623.108753
Name: goal, dtype: float64

In [41]:
df3["usd pledged"].groupby(df3["state"]).mean()

state
failed         1279.467288
successful    19442.292414
Name: usd pledged, dtype: float64

In [42]:
df3["backers"].groupby(df3["state"]).mean()

state
failed         16.768301
successful    253.665538
Name: backers, dtype: float64

In [43]:
df3["pct_funded"].groupby(df3["state"]).mean()

state
failed          8.894607
successful    674.295756
Name: pct_funded, dtype: float64

In [ ]:
# average number of backers and pledges by main category (pivot)
# include the variable "pct_funded" to values to get a better picture of the projects that met/exceeded their goal

# use the "pivot_table" function to view the following results

In [44]:
 pd.pivot_table(df3, index=["main_category"], values=["backers","usd pledged","pct_funded"])

                  backers  pct_funded   usd pledged
main_category
Art             42.541206  288.171129   3069.410309
Comics         145.676812  765.478859   6832.580096
Crafts          29.562441  309.386028   1514.296337
Dance           45.290454   85.553911   3424.076079
Design         268.927566  191.466794  23132.730636
Fashion         69.507418  100.535322   5665.158035
Film & Video    73.161697  146.030454   6518.644822
Food            59.249431   95.265222   5221.043908
Games          386.230282  844.868656  22622.060660
Journalism      43.399774   38.912989   2793.559315
Music           57.797494  407.374544   3930.182092
Photography     40.766036   60.139879   3265.703688
Publishing      57.901567  176.366619   3206.302548
Technology     187.457750  271.263750  20898.350418
Theater         49.613383  119.805148   4018.430797

In [ ]:
# average number of backers and pledges by main category and 
# subcategory (pivot) include the variable "pct_funded" to values 
# to get a better picture of the projects that met/exceeded their goal

# use the "pivot_table" function to view the following results

In [45]:
 pd.pivot_table(df3, index=["category"], values=["backers","usd pledged","pct_funded"])

                       backers   pct_funded   usd pledged
category
3D Printing         273.092308   195.028226  70321.848632
Academic             30.544068   202.940447   2003.564080
Accessories          99.114499   102.546350   7047.600829
Action               59.240404    57.357650   4128.312842
Animals              34.532663    62.111069   2382.214298
Animation           144.169215    57.837451  10161.303969
Anthologies         244.378906   155.132877   9707.767801
Apparel              56.851836   151.657277   4840.655465
Apps                 26.027861    61.525306   1589.148271
Architecture         54.474576    43.761053   5110.371215
Art                  46.567355   133.703097   3547.346218
Art Books           130.134277   294.944148   8497.157849
Audio                57.790614    51.393010   3798.740964
Bacon                27.803681    87.388254   1598.635068
Blues                51.968254    61.782423   3901.857626
Calendars            97.803828   106.214957   3274.572065
Camera Equipment    409.892430   239.599300  71126.629373
Candles              13.941368    35.405668    605.679972
Ceramics             52.522388    68.370812   4889.230446
Children's Books     59.756410    67.790570   3204.049558
Childrenswear        48.425397    31.505479   3730.010306
Chiptune            498.387097   180.277784  19654.133498
Civic Design        112.230088    53.288711  10104.483750
Classical Music      54.523466   112.277457   4528.904938
Comedy               92.905660    61.601662   6181.137441
Comic Books          89.528144  2232.975903   3277.407865
Comics              140.908834   256.197029   7009.820014
Community Gardens    21.817021    37.813335   1774.361231
Conceptual Art       29.964933  1352.879791   1682.404396
Cookbooks           100.599462   156.260901   5230.822925
Country & Folk       67.380005   130.821656   4739.995996
Couture              14.141361    30.017826   1534.816551
Crafts               33.384751    93.350913   1635.011491
Crochet               8.951220    54.090704    344.568518
DIY                  19.600506    40.831179    933.673297
DIY Electronics     314.456811  1880.617066  26395.598901
Dance                47.911142    93.334116   3618.409594
Design              182.312586   138.224537  13509.361754
Digital Art          36.511771   111.029703   2068.192840
Documentary          98.047042   222.620619   9012.627707
Drama                38.467471    55.467505   4317.194804
Drinks               63.926316    72.954679   6606.220018
Electronic Music     48.400241   197.949552   2671.848762
Embroidery           13.214286    27.626348    618.892421
Events               21.774411    38.282390   1709.839167
Experimental         29.133730    80.332798   1879.680929
Fabrication Tools    86.767857   123.057495  38635.618952
Faith                47.378713    63.573919   4223.476944
Family               48.727273    27.521313   5090.511233
Fantasy             143.211454    51.208947  11865.339980
Farmer's Markets     19.003135    27.531367   1903.061146
Farms                34.874713    30.433120   3744.831300
Fashion              74.479062    78.179449   5852.238444
Festivals            39.858255    87.580482   2992.783911
Fiction              30.908754    54.089324   1558.491226
Film & Video         53.579291   157.678487   4930.303051
Fine Art             29.224199   103.587836   2461.953439
Flight              162.337793    78.324092  28325.768377
Food                 72.000314   129.347085   6240.742036
Food Trucks          23.356383    19.079287   2112.549996
Footwear            149.713222   110.163939  15131.907236
Gadgets             347.641375   575.746733  29106.489521
Games               101.226494   335.582900   7741.528588
Gaming Hardware     467.385321   631.920601  69561.516705
Glass                19.844037    55.841164   1513.935062
Graphic Design      111.395522   332.061117   5852.275416
Graphic Novels      166.026734   944.420641   7963.044127
Hardware            369.767790   545.474665  44317.869397
Hip-Hop              21.943174    78.036896   1225.317680
Horror               50.002299   109.634449   5671.410567
Illustration         64.163498   233.162280   3090.818141
Immersive            51.665272    79.785355   4941.707966
Indie Rock           63.709588   215.541250   3985.325850
Installations        53.734286    84.257455   4423.914391
Interactive Design   52.261484   831.683076   5249.699127
Jazz                 59.378721   118.285459   4499.483700
Jewelry              27.879781    61.884407   2776.702660
Journalism           48.015406    47.504769   3076.977927
Kids                 66.504673   174.150151   4453.162691
Knitting             66.785185   107.893032   3991.926166
Latin                38.977528   933.358056   3797.561608
Letterpress          91.941176   170.524714   5834.528939
Literary Journals    76.270408    86.368794   3035.786078
Live Games           23.134286    34.697890   1667.651710
Makerspaces          72.554878    75.350483   7046.755159
Metal                49.936709   785.039989   2322.802257
Mixed Media          33.124371    65.357023   2866.891416
Mobile Games         20.528674    25.995110   1066.053893
Movie Theaters       94.518072    31.651923   8178.006865
Music                68.676657  1085.838258   4782.225743
Music Videos         27.253876    47.932120   1888.110207
Musical              54.311047   340.829765   5213.545079
Narrative Film      115.330159   288.191577  11369.790324
Nature               17.705882    30.128893   1441.599734
Nonfiction           47.689409    58.421888   2948.978014
Painting             22.831882    90.397884   1862.313411
People               30.724138    36.042031   2031.026196
Performance Art      32.130623    66.133471   2340.126200
Performances         41.119110    74.718245   3067.980283
Periodicals          99.889529    70.222648   5660.466840
Pet Fashion          33.879121    67.712932   3085.858602
Photo                26.788732    50.940675   1814.252706
Photobooks           79.608534    72.737603   7073.492690
Photography          40.532037    60.840355   3195.777514
Places               13.522686    42.718202    821.104104
Playing Cards       182.490552   413.513768   7206.851421
Plays                37.335835    93.341494   2891.757038
Poetry               26.572072   140.407974   1289.202604
Pop                  57.358306   208.036166   4030.155877
Pottery              58.215385    91.758675   3583.771604
Print                45.936047    36.663700   2590.594711
Printing             22.277027  8542.339385    865.445505
Product Design      316.092372   182.927465  27991.847656
Public Art           57.112424    86.644675   4238.759408
Publishing           61.768411   101.161952   3414.288085
Punk                 37.449074   251.686023   1836.191462
Puzzles             142.264151   124.512307   5855.381654
Quilts               23.390625    46.274137   1647.641411
R&B                  27.605769    34.197360   2043.620037
Radio & Podcasts    166.995940  3195.044068   7464.351176
Ready-to-wear        36.034423    59.530023   3585.828072
Residencies          40.288462    80.615014   2963.146585
Restaurants          39.533300    23.451078   4615.734552
Robots              199.255263   332.638579  31186.770102
Rock                 51.092960   171.512852   3390.401865
Romance              44.725191    56.001674   3861.684408
Science Fiction     100.930368    62.863888   8706.260996
Sculpture            41.692153  1969.751523   3315.002704
Shorts               39.051085    93.296035   3482.595222
Small Batch          54.214341   160.448817   3772.465191
Software             87.462361   107.153357   4126.172203
Sound               399.655527   147.332791  66289.121490
Space Exploration   387.115556    87.613173  28297.454583
Spaces               80.831010    53.897210   7374.277221
Stationery           54.944444   154.327239   1379.982363
Tabletop Games      478.161721  1382.589443  31866.666273
Taxidermy            48.555556    90.387291   4071.061114
Technology          187.672173   250.682961  20652.934517
Television           93.519041    25.149110  11160.145077
Textiles             24.451429    84.086912   1709.769996
Theater              50.660593   106.753333   4050.061876
Thrillers            43.109091    47.564394   4813.604712
Translations         40.626087    55.191641   2615.556503
Typography          395.042254   194.629470  28549.630735
Vegan                95.272973    60.292184   5787.616581
Video                17.450331    17.969104   1407.668924
Video Art            26.757143    36.329359   3329.087411
Video Games         483.715157   665.343751  22986.210000
Wearables           431.093023   162.813486  47650.043765
Weaving              17.745763    58.801723   1029.554598
Web                  56.842241    29.000947   3376.823987
Webcomics           275.403263   155.908649  12360.386881
Webseries            60.160939    81.082775   4355.481034
Woodworking          22.099762   304.034601   1549.588085
Workshops            21.630252    56.203796   1357.862474
World Music          58.424650    72.932091   3702.566343
Young Adult          23.413732   638.218353   1383.475593
Zines                53.453488   113.438971   2125.691922

In [66]:
## state by campaign main category (crosstab)
# hint: list 'state' second for an easier to read table

# HINT: it's easier to understand the differences between groups by 
# looking at percentages; use the following code example to transform 
# crosstab numbers into percentages

## pd.crosstab(df['var1'], df['var2'], normalize='index')

#use the "crosstab" function to view the following results

In [46]:
pd.crosstab(df3["main_category"], df3["state"])

state          failed  successful
main_category
Art             12128        9677
Comics           3411        4507
Crafts           4637        1673
Dance            1091        2104
Design          12063        7969
Fashion         11520        4319
Film & Video    29696       21412
Food            13632        5267
Games           13033        9396
Journalism       2667         870
Music           19172       21696
Photography      5760        2908
Publishing      19973       10281
Technology      16377        5067
Theater          3343        5997

In [47]:
## state by campaign sub-category (crosstab)
# hint: list 'state' second for an easier to read table

pd.crosstab(df3["category"], df3["state"])

state               failed  successful
category
3D Printing            262         193
Academic               442         148
Accessories           1141         597
Action                 418          77
Animals                144          55
Animation             1365         597
Anthologies            154         358
Apparel               3636        1021
Apps                  3698         286
Architecture           391         140
Art                   3452        2791
Art Books              949        1099
Audio                  198          79
Bacon                  126          37
Blues                   98          91
Calendars              112          97
Camera Equipment       114         137
Candles                261          46
Ceramics               109          92
Children's Books      3273        1875
Childrenswear          249          66
Chiptune                 6          25
Civic Design           141          85
Classical Music        712        1504
Comedy                 892         645
Comic Books            635        1035
Comics                1974        2271
Community Gardens      174          61
Conceptual Art         496         331
Cookbooks              273          99
Country & Folk        1290        2531
Couture                153          38
Crafts                2478         932
Crochet                101          22
DIY                    651         140
DIY Electronics        283         319
Dance                  634        1493
Design                1800        1108
Digital Art            671         306
Documentary           7912        5459
Drama                  876         615
Drinks                1169         446
Electronic Music      1045         614
Embroidery              60          10
Events                 468         126
Experimental           387         286
Fabrication Tools      118          50
Faith                  446         362
Family                 186          56
Fantasy                150          77
Farmer's Markets       263          56
Farms                  671         199
Fashion               4928        2069
Festivals              253         389
Fiction               5283        1994
Film & Video          5036        2777
Fine Art               325         237
Flight                 232          67
Food                  6443        3102
Food Trucks           1129         187
Footwear               342         195
Gadgets               1116         571
Games                 1537         622
Gaming Hardware        155          63
Glass                   76          33
Graphic Design         878         596
Graphic Novels         502         695
Hardware              1625        1045
Hip-Hop               2515         547
Horror                 575         295
Illustration           992        1112
Immersive              101         138
Indie Rock            1606        3442
Installations          156         194
Interactive Design     217          66
Jazz                   583         996
Jewelry                541         191
Journalism             988         440
Kids                   109         105
Knitting                67          68
Latin                   57          32
Letterpress             11          23
Literary Journals       97          99
Live Games             555         145
Makerspaces            100          64
Metal                  319         234
Mixed Media           1369         818
Mobile Games          1002         114
Movie Theaters         125          41
Music                 5269        5475
Music Videos           319         197
Musical                294         394
Narrative Film        2520        1890
Nature                 342          83
Nonfiction            4620        1961
Painting              1648         993
People                 629         183
Performance Art        971         874
Performances           283         481
Periodicals            581         460
Pet Fashion             60          31
Photo                  113          29
Photobooks             623         455
Photography           3243        1798
Places                 454          97
Playing Cards          738         638
Plays                  405         661
Poetry                 684         426
Pop                   1339        1424
Pottery                 30          35
Print                  384         132
Printing               109          39
Product Design        8613        5926
Public Art            1186        1438
Publishing            2797        1331
Punk                   102         114
Puzzles                 89          70
Quilts                  49          15
R&B                    231          81
Radio & Podcasts       388         351
Ready-to-wear          470         111
Residencies             15          37
Restaurants           1686         341
Robots                 209         171
Rock                  2575        3277
Romance                 85          46
Science Fiction        296         221
Sculpture              855         636
Shorts                4469        6317
Small Batch            876         421
Software              1822         330
Sound                  205         184
Space Exploration      128          97
Spaces                 351         223
Stationery              85          59
Tabletop Games        3092        5738
Taxidermy                5           4
Technology            3657        1065
Television             581         128
Textiles               122          53
Theater               2202        4274
Thrillers              341         154
Translations            82          33
Typography              23          48
Vegan                  232         138
Video                  266          36
Video Art              101          39
Video Games           5865        2006
Wearables              417         271
Weaving                 41          18
Web                   3109         371
Webcomics              168         261
Webseries             3176        1596
Woodworking            613         229
Workshops               79          40
World Music            870         842
Young Adult            430         138
Zines                  139         119

## Part 5: Summerize Your Findings

By now, your group should feel very comfortable with the aspects of the Kickstarter dataset. You should have a firm understanding of what Kickstarter is, what the dataset contains, the characteristics of each variable, how the variables interact with each other, and finally, which variables influence the outcome of the Kickstarter campaign. Can you put all this information together to tell a story about the data? Your presentation should include clear answers to the two primary questions:

    1. What kinds of projects should the Kickstarter Marking Team focus their attention on?
    2. Why should the Marketing Team focus their attention in that direction?

In addition to these two questions, your presentation should cover the additional questions listed below. These questions should be easy to answer using the information you discovered above. When you are done, submit your completed notebook to me and have your presentation ready to present to the class.   

### <font color=#6AA121>Questions to Answer</font>
1.	What main category is the most profitable (highest amount of money pledged)? 
2.	Which main category is the most popular (highest number of backers)?
3.	Which sub-categories are the most profitable and popular (top 3)?
4.	What are some of the characteristics of a successful Kickstarter campaign? 
5.	How does the success or failure of Kickstarter campaigns differ between main category, sub-category, country, and length of campaign? Please mention only the most notable – you do not need to detail the success/failure rate for each category/sub-category? 

***

### <font color=#306EFF>TIPS FOR A GREAT PRESENTATION</font>

* Start with the most important information (answers to the two questions above), and work backwards. The entire class will be working with the same dataset, therefore, we don't need to know the details of all your coding -- we just want to know what findings are most important to the questions. 
* Create clear visualizations. Make sure your audience can quickly and easily understand what your visualizations are showing. While you have a lot of options for how to style your visualizations, don't go overboard! 
* Make sure everyone understands what the visualization is showing; it should not have to stand on its own. When you present a visualization, you should be able to discuss what it means and what the significance is. 
* Use a single presentation format -- you can create a PowerPoint presentation, or show individual (or a dashboard) visualizations and talk through what they mean. Regardless of what you use, make sure you are only using ONE and not flipping back and forth between different software.

In [48]:
#use the "groupby" function to view the following results
df3["usd pledged"].groupby(df3["main_category"]).sum()

main_category
Art             6.692849e+07
Comics          5.410037e+07
Crafts          9.555210e+06
Dance           1.093992e+07
Design          4.633949e+08
Fashion         8.973044e+07
Film & Video    3.331549e+08
Food            9.867251e+07
Games           5.073902e+08
Journalism      9.880819e+06
Music           1.606187e+08
Photography     2.830712e+07
Publishing      9.700348e+07
Technology      4.481442e+08
Theater         3.753214e+07
Name: usd pledged, dtype: float64

In [49]:
df3["usd pledged"].groupby(df3["main_category"]).mean()

main_category
Art              3069.410309
Comics           6832.580096
Crafts           1514.296337
Dance            3424.076079
Design          23132.730636
Fashion          5665.158035
Film & Video     6518.644822
Food             5221.043908
Games           22622.060660
Journalism       2793.559315
Music            3930.182092
Photography      3265.703688
Publishing       3206.302548
Technology      20898.350418
Theater          4018.430797
Name: usd pledged, dtype: float64

In [ ]:
# 1) What main category is the most profitable (highest amount of money pledged)?

In [ ]:
# By total amount, "Art" has raised the most money ($66,928,490). By average (mean), "Design" has raised the most money
# ($23132.730636)

In [50]:
df3["backers"].groupby(df3["main_category"]).sum()

main_category
Art              927611
Comics          1153469
Crafts           186539
Dance            144703
Design          5387157
Fashion         1100928
Film & Video    3739148
Food            1119755
Games           8662759
Journalism       153505
Music           2362068
Photography      353360
Publishing      1751754
Technology      4019844
Theater          463389
Name: backers, dtype: int64

In [ ]:
# 2) Which main category is the most popular (highest number of backers)?

In [ ]:
# "Games" has the highest number of backers (8,662,759)

In [51]:
df3["usd pledged"].groupby(df3["category"]).sum()

category
3D Printing           3.199644e+07
Academic              1.182103e+06
Accessories           1.224873e+07
Action                2.043515e+06
Animals               4.740606e+05
Animation             1.993648e+07
Anthologies           4.970377e+06
Apparel               2.254293e+07
Apps                  6.331167e+06
Architecture          2.713607e+06
Art                   2.214608e+07
Art Books             1.740218e+07
Audio                 1.052251e+06
Bacon                 2.605775e+05
Blues                 7.374511e+05
Calendars             6.843856e+05
Camera Equipment      1.785278e+07
Candles               1.859438e+05
Ceramics              9.827353e+05
Children's Books      1.649445e+07
Childrenswear         1.174953e+06
Chiptune              6.092781e+05
Civic Design          2.283613e+06
Classical Music       1.003605e+07
Comedy                9.500408e+06
Comic Books           5.473271e+06
Comics                2.975669e+07
Community Gardens     4.169749e+05
Conceptual Art        1.391348e+06
Cookbooks             1.945866e+06
Country & Folk        1.811152e+07
Couture               2.931500e+05
Crafts                5.575389e+06
Crochet               4.238193e+04
DIY                   7.385356e+05
DIY Electronics       1.589015e+07
Dance                 7.696357e+06
Design                3.928522e+07
Digital Art           2.020624e+06
Documentary           1.205078e+08
Drama                 6.436937e+06
Drinks                1.066905e+07
Electronic Music      4.432597e+06
Embroidery            4.332247e+04
Events                1.015644e+06
Experimental          1.265025e+06
Fabrication Tools     6.490784e+06
Faith                 3.412569e+06
Family                1.231904e+06
Fantasy               2.693432e+06
Farmer's Markets      6.070765e+05
Farms                 3.258003e+06
Fashion               4.094811e+07
Festivals             1.921367e+06
Fiction               1.134114e+07
Film & Video          3.852046e+07
Fine Art              1.383618e+06
Flight                8.469405e+06
Food                  5.956788e+07
Food Trucks           2.780116e+06
Footwear              8.125834e+06
Gadgets               4.910265e+07
Games                 1.671396e+07
Gaming Hardware       1.516441e+07
Glass                 1.650189e+05
Graphic Design        8.626254e+06
Graphic Novels        9.531764e+06
Hardware              1.183287e+08
Hip-Hop               3.751923e+06
Horror                4.934127e+06
Illustration          6.503081e+06
Immersive             1.181068e+06
Indie Rock            2.011792e+07
Installations         1.548370e+06
Interactive Design    1.485665e+06
Jazz                  7.104685e+06
Jewelry               2.032546e+06
Journalism            4.393924e+06
Kids                  9.529768e+05
Knitting              5.389100e+05
Latin                 3.379830e+05
Letterpress           1.983740e+05
Literary Journals     5.950141e+05
Live Games            1.167356e+06
Makerspaces           1.155668e+06
Metal                 1.284510e+06
Mixed Media           6.269892e+06
Mobile Games          1.189716e+06
Movie Theaters        1.357549e+06
Music                 5.138023e+07
Music Videos          9.742649e+05
Musical               3.586919e+06
Narrative Film        5.014078e+07
Nature                6.126799e+05
Nonfiction            1.940722e+07
Painting              4.918370e+06
People                1.649193e+06
Performance Art       4.317533e+06
Performances          2.343937e+06
Periodicals           5.892546e+06
Pet Fashion           2.808131e+05
Photo                 2.576239e+05
Photobooks            7.625225e+06
Photography           1.610991e+07
Places                4.524284e+05
Playing Cards         9.916628e+06
Plays                 3.082613e+06
Poetry                1.431015e+06
Pop                   1.113532e+07
Pottery               2.329452e+05
Print                 1.336747e+06
Printing              1.280859e+05
Product Design        4.069735e+08
Public Art            1.112250e+07
Publishing            1.409418e+07
Punk                  3.966174e+05
Puzzles               9.310057e+05
Quilts                1.054491e+05
R&B                   6.376095e+05
Radio & Podcasts      5.516156e+06
Ready-to-wear         2.083366e+06
Residencies           1.540836e+05
Restaurants           9.356094e+06
Robots                1.185097e+07
Rock                  1.984063e+07
Romance               5.058807e+05
Science Fiction       4.501137e+06
Sculpture             4.942669e+06
Shorts                3.756327e+07
Small Batch           4.892887e+06
Software              8.879523e+06
Sound                 2.578647e+07
Space Exploration     6.366927e+06
Spaces                4.232835e+06
Stationery            1.987175e+05
Tabletop Games        2.813827e+08
Taxidermy             3.663955e+04
Technology            9.752316e+07
Television            7.912543e+06
Textiles              2.992097e+05
Theater               2.622820e+07
Thrillers             2.382734e+06
Translations          3.007890e+05
Typography            2.027024e+06
Vegan                 2.141418e+06
Video                 4.251160e+05
Video Art             4.660722e+05
Video Games           1.809245e+08
Wearables             3.278323e+07
Weaving               6.074372e+04
Web                   1.175135e+07
Webcomics             5.302606e+06
Webseries             2.078436e+07
Woodworking           1.304753e+06
Workshops             1.615856e+05
World Music           6.338794e+06
Young Adult           7.858141e+05
Zines                 5.484285e+05
Name: usd pledged, dtype: float64

In [52]:
df3["usd pledged"].groupby(df3["category"]).mean()

category
3D Printing           70321.848632
Academic               2003.564080
Accessories            7047.600829
Action                 4128.312842
Animals                2382.214298
Animation             10161.303969
Anthologies            9707.767801
Apparel                4840.655465
Apps                   1589.148271
Architecture           5110.371215
Art                    3547.346218
Art Books              8497.157849
Audio                  3798.740964
Bacon                  1598.635068
Blues                  3901.857626
Calendars              3274.572065
Camera Equipment      71126.629373
Candles                 605.679972
Ceramics               4889.230446
Children's Books       3204.049558
Childrenswear          3730.010306
Chiptune              19654.133498
Civic Design          10104.483750
Classical Music        4528.904938
Comedy                 6181.137441
Comic Books            3277.407865
Comics                 7009.820014
Community Gardens      1774.361231
Conceptual Art         1682.404396
Cookbooks              5230.822925
Country & Folk         4739.995996
Couture                1534.816551
Crafts                 1635.011491
Crochet                 344.568518
DIY                     933.673297
DIY Electronics       26395.598901
Dance                  3618.409594
Design                13509.361754
Digital Art            2068.192840
Documentary            9012.627707
Drama                  4317.194804
Drinks                 6606.220018
Electronic Music       2671.848762
Embroidery              618.892421
Events                 1709.839167
Experimental           1879.680929
Fabrication Tools     38635.618952
Faith                  4223.476944
Family                 5090.511233
Fantasy               11865.339980
Farmer's Markets       1903.061146
Farms                  3744.831300
Fashion                5852.238444
Festivals              2992.783911
Fiction                1558.491226
Film & Video           4930.303051
Fine Art               2461.953439
Flight                28325.768377
Food                   6240.742036
Food Trucks            2112.549996
Footwear              15131.907236
Gadgets               29106.489521
Games                  7741.528588
Gaming Hardware       69561.516705
Glass                  1513.935062
Graphic Design         5852.275416
Graphic Novels         7963.044127
Hardware              44317.869397
Hip-Hop                1225.317680
Horror                 5671.410567
Illustration           3090.818141
Immersive              4941.707966
Indie Rock             3985.325850
Installations          4423.914391
Interactive Design     5249.699127
Jazz                   4499.483700
Jewelry                2776.702660
Journalism             3076.977927
Kids                   4453.162691
Knitting               3991.926166
Latin                  3797.561608
Letterpress            5834.528939
Literary Journals      3035.786078
Live Games             1667.651710
Makerspaces            7046.755159
Metal                  2322.802257
Mixed Media            2866.891416
Mobile Games           1066.053893
Movie Theaters         8178.006865
Music                  4782.225743
Music Videos           1888.110207
Musical                5213.545079
Narrative Film        11369.790324
Nature                 1441.599734
Nonfiction             2948.978014
Painting               1862.313411
People                 2031.026196
Performance Art        2340.126200
Performances           3067.980283
Periodicals            5660.466840
Pet Fashion            3085.858602
Photo                  1814.252706
Photobooks             7073.492690
Photography            3195.777514
Places                  821.104104
Playing Cards          7206.851421
Plays                  2891.757038
Poetry                 1289.202604
Pop                    4030.155877
Pottery                3583.771604
Print                  2590.594711
Printing                865.445505
Product Design        27991.847656
Public Art             4238.759408
Publishing             3414.288085
Punk                   1836.191462
Puzzles                5855.381654
Quilts                 1647.641411
R&B                    2043.620037
Radio & Podcasts       7464.351176
Ready-to-wear          3585.828072
Residencies            2963.146585
Restaurants            4615.734552
Robots                31186.770102
Rock                   3390.401865
Romance                3861.684408
Science Fiction        8706.260996
Sculpture              3315.002704
Shorts                 3482.595222
Small Batch            3772.465191
Software               4126.172203
Sound                 66289.121490
Space Exploration     28297.454583
Spaces                 7374.277221
Stationery             1379.982363
Tabletop Games        31866.666273
Taxidermy              4071.061114
Technology            20652.934517
Television            11160.145077
Textiles               1709.769996
Theater                4050.061876
Thrillers              4813.604712
Translations           2615.556503
Typography            28549.630735
Vegan                  5787.616581
Video                  1407.668924
Video Art              3329.087411
Video Games           22986.210000
Wearables             47650.043765
Weaving                1029.554598
Web                    3376.823987
Webcomics             12360.386881
Webseries              4355.481034
Woodworking            1549.588085
Workshops              1357.862474
World Music            3702.566343
Young Adult            1383.475593
Zines                  2125.691922
Name: usd pledged, dtype: float64

In [53]:
df3["backers"].groupby(df3["category"]).sum()

category
3D Printing            124257
Academic                18021
Accessories            172261
Action                  29324
Animals                  6872
Animation              282860
Anthologies            125122
Apparel                264759
Apps                   103695
Architecture            28926
Art                    290720
Art Books              266515
Audio                   16008
Bacon                    4532
Blues                    9822
Calendars               20441
Camera Equipment       102883
Candles                  4280
Ceramics                10557
Children's Books       307626
Childrenswear           15254
Chiptune                15450
Civic Design            25364
Classical Music        120824
Comedy                 142796
Comic Books            149512
Comics                 598158
Community Gardens        5127
Conceptual Art          24781
Cookbooks               37423
Country & Folk         257459
Couture                  2701
Crafts                 113842
Crochet                  1101
DIY                     15504
DIY Electronics        189303
Dance                  101907
Design                 530165
Digital Art             35672
Documentary           1310987
Drama                   57355
Drinks                 103241
Electronic Music        80296
Embroidery                925
Events                  12934
Experimental            19607
Fabrication Tools       14577
Faith                   38282
Family                  11792
Fantasy                 32509
Farmer's Markets         6062
Farms                   30341
Fashion                521130
Festivals               25589
Fiction                224923
Film & Video           418615
Fine Art                16424
Flight                  48539
Food                   687243
Food Trucks             30737
Footwear                80396
Gadgets                586471
Games                  218548
Gaming Hardware        101890
Glass                    2163
Graphic Design         164197
Graphic Novels         198734
Hardware               987280
Hip-Hop                 67190
Horror                  43502
Illustration           135000
Immersive               12348
Indie Rock             321606
Installations           18807
Interactive Design      14790
Jazz                    93759
Jewelry                 20408
Journalism              68566
Kids                    14232
Knitting                 9016
Latin                    3469
Letterpress              3126
Literary Journals       14949
Live Games              16194
Makerspaces             11899
Metal                   27615
Mixed Media             72443
Mobile Games            22910
Movie Theaters          15690
Music                  737862
Music Videos            14063
Musical                 37366
Narrative Film         508606
Nature                   7525
Nonfiction             313844
Painting                60299
People                  24948
Performance Art         59281
Performances            31415
Periodicals            103985
Pet Fashion              3083
Photo                    3804
Photobooks              85818
Photography            204322
Places                   7451
Playing Cards          251107
Plays                   39800
Poetry                  29495
Pop                    158481
Pottery                  3784
Print                   23703
Printing                 3297
Product Design        4595667
Public Art             149863
Publishing             254980
Punk                     8089
Puzzles                 22620
Quilts                   1497
R&B                      8613
Radio & Podcasts       123410
Ready-to-wear           20936
Residencies              2095
Restaurants             80134
Robots                  75717
Rock                   298996
Romance                  5859
Science Fiction         52181
Sculpture               62163
Shorts                 421205
Small Batch             70316
Software               188219
Sound                  155466
Space Exploration       87101
Spaces                  46397
Stationery               7912
Tabletop Games        4222168
Taxidermy                 437
Technology             886188
Television              66305
Textiles                 4279
Theater                328078
Thrillers               21339
Translations             4672
Typography              28048
Vegan                   35251
Video                    5270
Video Art                3746
Video Games           3807322
Wearables              296592
Weaving                  1047
Web                    197811
Webcomics              118148
Webseries              287088
Woodworking             18608
Workshops                2574
World Music            100023
Young Adult             13299
Zines                   13791
Name: backers, dtype: int64

In [ ]:
# 3) Which sub-categories are the most profitable and popular (top 3)?

In [54]:
# The sub-categories that raised the most money:
# by total (sum): 
#     Product Design ($406,973,500)
#     Tabletop Games ($281,382,700)
#     Video Games ($180,924,500)

# by average (mean):
#     3D Printing ($70321.848632)
#     Gaming Hardware ($69561.516705)
#     Sound  ($66289.121490)

# The most popular sub-categories (by # of backers):
#      Product Design (4,595,667)
#      Tabletop Games (4,222,168)
#      Video Games (3,807,322)

In [ ]:
# 4) What are some of the characteristics of a successful Kickstarter campaign?

In [ ]:
# 5) How does the success or failure of Kickstarter campaigns differ between main category, 
# sub-category, country, and length of campaign? Please mention only the most notable – you do not need to 
# detail the success/failure rate for each category/sub-category?